#########################
# Overlay combinations: #
#   - 1080p             #
#   - 1080p HDR         #
#########################

collections:
  1080p:
    plex_search:
      all:
        resolution: 1080p
        hdr: false
    item_overlay: 
      name: 1080p
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/HD/1080p.png
    build_collection: false
    #revert_overlay: true

  1080p-HDR:
    plex_search:
      all:
        resolution: 1080p
        hdr: true
    item_overlay: 
      name: 1080p-HDR
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/HD/1080p-HDR.png
    build_collection: false
    #revert_overlay: true
