#########################
# Overlay combinations: #
#   - 4K                #
#   - 4K HDR            #
#   - 4K + Audio        #
#   - 4K HDR + Audio    #
#########################

collections:
  4K:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath.not:
      - AC3
      - EAC3
      - TrueHD
      - Atmos
      - DTS-X
      - DTS-HD
    item_overlay: 
      name: 4K
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K.png
    build_collection: false
    #revert_overlay: true

  4K-HDR:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath.not:
      - AC3
      - EAC3
      - TrueHD
      - Atmos
      - DTS-X
      - DTS-HD
    item_overlay: 
      name: 4K-HDR
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR.png
    build_collection: false
    #revert_overlay: true

  4K-IMAX:
    plex_search:
      all:
        resolution: 4K
    filters:
      filepath: Imax
    item_overlay: 
      name: 4K-IMAX
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-IMAX.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-IMAX:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: Imax
    item_overlay: 
      name: 4K-HDR-IMAX
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-IMAX.png
    build_collection: false
    #revert_overlay: true

  4K-DolbyDigital:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath: AC3
      filepath.not: EAC3
    item_overlay: 
      name: 4K-DolbyDigital
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-DolbyDigital.png
    build_collection: false
    #revert_overlay: true

  4K-DolbyDigitalPlus:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath: EAC3
      filepath.not: Atmos
    item_overlay: 
      name: 4K-DolbyDigitalPlus
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-DolbyDigitalPlus.png
    build_collection: false
    #revert_overlay: true

  4K-DolbyDigitalPlusAtmos:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath: Atmos
      filepath.not: TrueHD
    item_overlay: 
      name: 4K-DolbyDigitalPlusAtmos
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-DolbyDigitalPlusAtmos.png
    build_collection: false
    #revert_overlay: true

  4K-DolbyTrueHD:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath: TrueHD
      filepath.not: Atmos
    item_overlay: 
      name: 4K-DolbyTrueHD
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-DolbyTrueHD.png
    build_collection: false
    #revert_overlay: true

  4K-DolbyTrueHDAtmos:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath: Atmos
      filepath.not: EAC3
    item_overlay: 
      name: 4K-DolbyTrueHDAtmos
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-DolbyTrueHDAtmos.png
    build_collection: false
    #revert_overlay: true

  4K-dtsX:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath: DTS-X
    item_overlay: 
      name: 4K-dtsX
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-dtsX.png
    build_collection: false
    #revert_overlay: true

  4K-dtsHD:
    plex_search:
      all:
        resolution: 4K
        hdr: false
    filters:
      filepath: DTS-HD MA
    item_overlay: 
      name: 4K-dtsHD
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-dtsHD.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-DolbyDigital:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: AC3
      filepath.not: EAC3
    item_overlay: 
      name: 4K-HDR-DolbyDigital
      url: https://https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-DolbyDigital.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-DolbyDigitalPlus:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: EAC3
      filepath.not: Atmos
    item_overlay: 
      name: 4K-HDR-DolbyDigitalPlus
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-DolbyDigitalPlus.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-DolbyDigitalPlusAtmos:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: Atmos
      filepath.not: TrueHD
    item_overlay: 
      name: 4K-HDR-DolbyDigitalPlusAtmos
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-DolbyDigitalPlusAtmos.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-DolbyTrueHD:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: TrueHD
      filepath.not: Atmos
    item_overlay: 
      name: 4K-HDR-DolbyTrueHD
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-DolbyTrueHD.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-DolbyTrueHDAtmos:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: Atmos
      filepath.not: EAC3
    item_overlay: 
      name: 4K-HDR-DolbyTrueHDAtmos
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-DolbyTrueHDAtmos.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-dtsX:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: DTS-X
    item_overlay: 
      name: 4K-HDR-dtsX
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-dtsX.png
    build_collection: false
    #revert_overlay: true

  4K-HDR-dtsHD:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    filters:
      filepath: DTS-HD MA
    item_overlay: 
      name: 4K-HDR-dtsHD
      url: https://raw.githubusercontent.com/bradmartti/Plex-Meta-Manager-Configs/master/bradmartti/Overlays/Images/UHD/4K-HDR-dtsHD.png
    build_collection: false
    #revert_overlay: true
